---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

executors:
  packer:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors_packer/packer:latest

jobs:
  build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Get Ansible Playbooks
          command: |
            git clone https://github.com/ansible-playbooks-centos7/redmine_install.git
            git clone https://github.com/ansible-playbooks-centos7/system.git
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Show Ansible version
          command: ansible --version
      - run:
          name: Packer build
          command: |
            TAG_NAME="redmine_golden_image `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"

            packer build \
            -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
            -var "aws_region=${AWS_DEFAULT_REGION}" \
            -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -var "tag_name=${TAG_NAME}" \
            build.json

workflows:
  version: 2.1
  packer:
    jobs:
      - build:
          context: AMI
