version: 2.1

executors:
  packer:
    docker:
      - image: circleci/golang
    working_directory: /tmp/packer

jobs:

  build:
    executor: packer

    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            sudo sudo apt-get update
            sudo apt-get install python3-pip
      - run:
          name: Install Packer
          command: |
            mkdir -p $(go env GOPATH)/src/github.com/hashicorp && cd $_
            git clone https://github.com/hashicorp/packer.git
            cd packer
            make dev
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Install Ansible
          command: pip3 install ansible
      - run:
          name: Get Ansible Playbook
          command: git clone https://github.com/ansible-playbooks-centos7/redmine_install.git
      - run:
          name: Get AMI ID
          command: |
            git clone https://github.com/packer-tm/aws-ami_centos7.git
            cd aws-ami_centos7
            AMI_ID=`git branch -a | grep ami | awk -F'/' '{for (i = 1; i <= NF; i++) print $i;}' | grep ami || true`
            echo "export AMI_ID=${AMI_ID}" >> $BASH_ENV
      - run:
          name: Packer build
          command: |
            packer build \
            -var "ami_id=${AMI_ID}" \
            -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
            -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
            -var "aws_region=${AWS_DEFAULT_REGION}" \
            build.json

workflows:
  version: 2
  packer:
    jobs:
      - build:
          context: AMI
